language: php
php:
  - 5.5
  - 5.6
  - 7.0
script: "sh -c 'cd tests && php all_tests.php'"
notifications:
  recipients:
    - alessandro.fazzi@welaika.com
    - fabrizio.monti@welaika.com
    - federico.parodi@welaika.com
    - filippo.gangidino@welaika.com
    - matteo.piotto@welaika.com
    - stefano.pau@welaika.com
    - alessandra.cannata@welaika.com
